### ISSUE TITLE
Duplicate problems in Readme file

### ISSUE THREAD

**Issue by RabbitLee** [pig0726/LeetCode#4]
The related file is `/activity/20200805/README.md`.
In line 24 and 25, problem 8 and 9 are identical.

https://github.com/pig0726/LeetCode/blame/master/activity/20200805/README.md#L24-L25

**Comment by RabbitLee** [comment]
another problem in the same file, line 33: an unwanted  `/submissions/`  in the end of the URL

https://github.com/pig0726/LeetCode/blame/master/activity/20200805/README.md#L33

**Comment by pig0726** [comment]
Thanks for reporting the issues. I have replaced the repeated 'Self Dividing Numbers' problem with 'Count Primes'.
